import { Montserrat } from "next/font/google";
import {Redux} from '../provider/redux';
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="w-screen h-auto flex justify-center items-start">
          <Redux>
            {children}
          </Redux>
        </div>
      </body>
    </html>
  );
}
